---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik-sm
  namespace: traefik
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      name: traefik
  namespaceSelector:
    matchNames:
      - traefik
  endpoints:
    - port: http
      interval: 30s